;; Test by loading all tests.
(load "test-macros.scm")
(load "sequencetest.scm")
(load "fibotest.scm")
(load "quote-test.scm")
(load "envtest.scm")
(load "test-lists.scm")
(load "settest.scm")
(load "state-test.scm")
(load "test-files.scm")
(load "test-structs.scm")
